### ISSUE TITLE
Why immutable.js?

### ISSUE THREAD

**Issue by bschlenk** [sgnl/nodeku#12]
I don't really see the point in making the responses immutable. There is no performance gain to be had by doing this, and it makes dealing with the lists and maps a bit quirky as they don't behave like standard js objects. Anybody using this api should already know that the responses are readonly.

**Comment by sgnl** [comment]
Yeah I feel the same. I just did it just because. I'd remove it the next chance I get.

**Comment by Glavin001** [comment]
@sgnl is Immutable.js something you would like removed? If so, would you be interested in receiving a Pull Request or have you already started this work?

**Comment by sgnl** [comment]
@Glavin001 New version has landed on NPM

removed Immutable
the fix we talked about earlier should be there now (I forgot to bump the version so it may have not landed on NPM like I thought it did previously)

🍰
