### ISSUE TITLE
Tests aren't being run

### ISSUE THREAD

**Issue by bschlenk** [sgnl/nodeku#21]
I wrote a test for a pull request and realized it should have been failing, but it wasn't. The wrapper code that everything uses never actually runs the tests :P

This: 

```js
function wrapper(description) {
  test(description, async t => {
    const device = await Nodeku();
    t.truthy(device);
  });
}
```

should be this:

```js
function wrapper(description, func) {
  test(description, async t => {
    const device = await Nodeku();
    t.truthy(device);
    func(t, device);
  });
}
```

I would send a pull request, but updating it causes a few of the existing tests to fail.

**Comment by sgnl** [comment]
I'll have time to update this on the weekend. Thanks for reporting
